version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
    groups:
      github_actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
    groups:
      pip_dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/tests/integration/v4/requirer_charm/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
    groups:
      pip_dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/tests/integration/v4/provider_charm/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
    groups:
      pip_dependencies:
        patterns:
          - "*"
