name: CI for tls-certificates-interface V2

on:
  push:
    paths:
      - "lib/charms/tls_certificates_interface/v2/**"

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    with:
      version: v2
